version: '3.7'
services:
    sf6-php8:
        container_name: sf6-php8
        build: sf6-php8
        ports:
            - "9000:8000"
        volumes:
            - ./project:/var/www/html

    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_PASSWORD: ChangeMe
            POSTGRES_USER: symfony
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        ports:
            - "6543:5432"

volumes:
  db-data:
